apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  MONGODB_ROOT_PASSWORD: cm9vdDEyMw==
  MONGODB_USERNAME: c3dpbWxhbmU=
  MONGODB_PASSWORD: cGFzczEyMw==
  MONGODB_DATABASE: ZGF0YWJhc2U=