# Default values for swimlane-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  name: swimlane-app

image:
  repository: 368040456386.dkr.ecr.us-east-1.amazonaws.com/swimlane_app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 3000
  nodePort: 30000