apiVersion: v1
kind: Service
metadata:
  name: swimlane-app
  labels:
    app: swimlane-app
spec:
  selector:
      app: swimlane-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30000
  type: NodePort